MvcStok/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
namespace MvcStok.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        DbMvcStokEntities db = new DbMvcStokEntities();
        public ActionResult Index(string p)
        {
            //  var urunler = db.TblUrunler.Where(x=>x.DURUM==true).ToList();
            var urunler = db.TblUrunler.Where(x=>x.DURUM==true);
            if (!string.IsNullOrEmpty(p))
            {
                urunler = urunler.Where(x => x.AD.Contains(p) && x.DURUM == true);
            }
            return View(urunler.ToList());
        }
        [HttpGet]
        public ActionResult YeniUrun()
        {
            List<SelectListItem> urun = (from x in db.TblUrunler.ToList()
                                         select new SelectListItem
                                         {
                                             Text = x.AD,
                                             Value = x.ID.ToString(),
                                         }).ToList();
            ViewBag.drop1 = urun;
            return View();
        }
        [HttpPost]
        public ActionResult YeniUrun(TblUrunler t)
        {
            var ktgr = db.TblKategori.Where(x => x.ID == t.TblKategori.ID).FirstOrDefault();
            t.TblKategori = ktgr;
            db.TblUrunler.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UrunGetir(int id)
        {
            List<SelectListItem> kat = (from x in db.TblKategori.ToList()
                                        select new SelectListItem
                                        {
                                            Text = x.AD,
                                            Value = x.ID.ToString()
                                        }).ToList();
            var ktgr = db.TblUrunler.Find(id);
            ViewBag.urunkategori = kat;
            return View("UrunGetir", ktgr);
        }
        public ActionResult UrunGuncelle(TblUrunler p)
        {
            var urun = db.TblUrunler.Find(p.ID);
            urun.AD = p.AD;
            urun.MARKA = p.MARKA;
            urun.STOK = p.STOK;
            urun.SATISFIYAT = p.SATISFIYAT;
            urun.ALISFIYAT = p.ALISFIYAT;
            var ktg = db.TblKategori.Where(x => x.ID == p.TblKategori.ID).FirstOrDefault();
            urun.KATEGORI = ktg.ID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UrunSil(TblUrunler p)
        {
            var urunbul = db.TblUrunler.Find(p.ID);
            urunbul.DURUM = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Views/Urun/Index.cshtml
@using MvcStok.Models.Entity
@model List<TblUrunler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("Index", "Urun", FormMethod.Get))
{
    <p>
        Ürün Adı: @Html.TextBox("p")
        <input type="submit" value="Ara"/>
    </p>
}
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>AD</th>
        <th>MARKA</th>
        <th>STOK</th>
        <th>ALIŞ FİYAT</th>
        <th>SATIŞ FİYAT</th>
        <th>KATEGORİ</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.AD</td>
            <td>@x.MARKA</td>
            <td>@x.STOK</td>
            <td>@x.ALISFIYAT</td>
            <td>@x.SATISFIYAT</td>
            <td>@x.TblKategori.AD</td>
            <td>
                <a href="/Urun/UrunSil/@x.ID" class="btn btn-danger">SİL</a>
            </td>
            <td><a href="/Urun/UrunGetir/@x.ID" class="btn btn-success">GÜNCELLE</a></td>
        </tr>
    }
</table>
<a href="/Urun/YeniUrun/" class="btn btn-primary">YENİ ÜRÜN GİRİŞİ</a>

MvcStok/Views/Urun/UrunGetir.cshtml
@model MvcStok.Models.Entity.TblUrunler
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("UrunGuncelle", "Urun", FormMethod.Post))
{

    <h2>Ürün Güncelleme</h2>
    <br />
    @Html.HiddenFor(x => x.ID)
    <br />
    @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.MARKA, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.STOK, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.ALISFIYAT, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.SATISFIYAT, new { @class = "form-control" })
    <br />
    @Html.DropDownListFor(x => x.TblKategori.ID, (List<SelectListItem>)ViewBag.urunkategori, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>


}

MvcStok/Views/Urun/YeniUrun.cshtml
@model MvcStok.Models.Entity.TblUrunler
@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form method="post" class="form-group">
    <h2>Yeni Ürün Ekleme</h2>
    <br /><br />
    <label>Ürün Adı</label>
    @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })
    <br />
    <label>Marka</label>
    @Html.TextBoxFor(x => x.MARKA, new { @class = "form-control" })
    <br />
    <label>Stok</label>
    @Html.TextBoxFor(x => x.STOK, new { @class = "form-control" })
    <br />
    <label>Alış Fiyat</label>
    @Html.TextBoxFor(x => x.ALISFIYAT, new { @class = "form-control" })
    <br />
    <label>Satış Fiyat</label>
    @Html.TextBoxFor(x => x.SATISFIYAT, new { @class = "form-control" })
    <br />
    <label>Kategori</label>
    @Html.DropDownListFor(x=>x.TblKategori.ID,(List<SelectListItem>)ViewBag.drop,new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>

</form>