MvcStok/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MvcStok.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        DbMvcStokEntities db = new DbMvcStokEntities();
        [Authorize]
        public ActionResult Index(int sayfa=1)
        {
            var musteriliste =db.TblMusteri.Where(x=>x.DURUM==true).ToList().ToPagedList(sayfa,3);
            return View(musteriliste);
        }
        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(TblMusteri p)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            p.DURUM = true;
            db.TblMusteri.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriSil(TblMusteri p)
        {
            var mustbul = db.TblMusteri.Find(p.ID);
            mustbul.DURUM = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriGetir(int id)
        {
           var mus=db.TblMusteri.Find(id);
            return View("MusteriGetir",mus);
        }
        public ActionResult MusteriGuncelle(TblMusteri t)
        {
            var mus = db.TblMusteri.Find(t.ID);
            mus.AD = t.AD;
            mus.SOYAD=t.SOYAD;
            mus.SEHIR=t.SEHIR;
            mus.BAKIYE=t.BAKIYE;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/Views/Musteri/Index.cshtml
@using MvcStok.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TblMusteri>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>AD</th>
        <th>SOYAD</th>
        <th>ŞEHİR</th>
        <th>BAKİYE</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.AD</td>
            <td>@x.SOYAD</td>
            <td>@x.SEHIR</td>
            <td>@x.BAKIYE</td>
            <td>
                <a href="/Musteri/MusteriSil/@x.ID" class="btn btn-danger">SİL</a>
            </td>
            <td><a href="/Musteri/MusteriGetir/@x.ID" class="btn btn-success">GÜNCELLE</a></td>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model,sayfa=>Url.Action("Index",new {sayfa}))
<a href="/Musteri/YeniMusteri/" class="btn btn-primary">YENİ MÜŞTERİ</a>

MvcStok/Views/Musteri/MusteriGetir.cshtml
@model MvcStok.Models.Entity.TblMusteri
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("MusteriGuncelle", "Musteri", FormMethod.Post))
{

    <h2>Müşteri Güncelleme</h2>
    <br />
    @Html.HiddenFor(x => x.ID)
    <br />
    @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.SEHIR, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.BAKIYE, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>


}

MvcStok/Views/Musteri/YeniMusteri.cshtml
@model MvcStok.Models.Entity.TblMusteri
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form method="post" class="form-group">
    <h2>Yeni Müşteri Ekleme</h2>
    <br /><br />
    <label>Müşteri Adı:</label>
    @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.AD, "", new { @style = "color:red" })
    <br />
    <label>Müüşteri Soyadı:</label>
    @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.SOYAD, "", new { @style = "color:red" })
    <br />
    <label>Şehir:</label>
    @Html.TextBoxFor(x => x.SEHIR, new { @class = "form-control" })
    <br />
    <label>Alış Fiyat</label>
    @Html.TextBoxFor(x => x.BAKIYE, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>

</form>